#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

compiler:
 - gcc
 - clang

env:
 - CONFIGURATION=Dev
 - CONFIGURATION=Release

before_install:
 # upgrade compiler (we need at least g++-4.8 for C++11 features)
 - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo apt-get update --yes -qq
 - gcc_version=4.8
 - sudo apt-get install --yes gcc-${gcc_version} g++-${gcc_version}
 - gcc-${gcc_version} --version
 # make sure compiler executables point to the just installed version
 - sudo ln -sf /usr/bin/cpp-${gcc_version} /usr/bin/cpp
 - sudo ln -sf /usr/bin/gcc-${gcc_version} /usr/bin/gcc
 - sudo ln -sf /usr/bin/g++-${gcc_version} /usr/bin/g++
 # install dependencies
 - sudo apt-get install --yes make libboost-dev libboost-program-options-dev libprotobuf-dev protobuf-compiler pandoc

install:
 - cd ..
 - git clone https://github.com/osmcode/libosmium.git
 - git clone https://github.com/scrosby/OSM-binary.git
 - cd OSM-binary/src
 - make
 - sudo make install

script:
 - cd $TRAVIS_BUILD_DIR
 - mkdir build
 - cd build
 # GCC ignores the pragmas in the code that disable the "return-type" warning selectively, so use this workaround
 - if [ "${CXX}" = 'g++' ]; then WORKAROUND="-DCMAKE_CXX_FLAGS=-Wno-return-type"; else WORKAROUND=""; fi
 - cmake -LA -DCMAKE_BUILD_TYPE=${CONFIGURATION} ${WORKAROUND} ..
 - make VERBOSE=1
 - ctest --output-on-failure

